### ISSUE TITLE
Stops working when entering "Customize..."

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/responsive-bookmarks-toolbar#1]
Many thanks for this release! I've noticed that it stops working if I just enter the Customize Toolbar mode and exit. Confirmed this on a clean profile, too. Restarting the extension (or Pale Moon) makes it work again.

**Comment by JustOff** [comment]
Resolved by [2.0.1](https://github.com/JustOff/responsive-bookmarks-toolbar/releases/tag/2.0.1).
